apiVersion: v1
kind: Secret
metadata:
  labels:
    app: release-name-mysql
    chart: mysql-1.3.2
    heritage: Tiller
    release: release-name
  name: release-name-mysql
  namespace: default
stringData:
  mysql-password: ref+vault://mehmet/crediantial#/password
  mysql-root-password: ref+vault://mehmet/crediantial#/password
type: Opaque